# Generated by Django 2.0.1 on 2018-01-22 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import sensor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hardware_name', models.CharField(max_length=120)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('pm2_5', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('pm10', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('pressure', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to=sensor.models.generate_path)),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensor_data', to='sensor.Sensor')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
